/**
 * File classes (BUILD_PROMPT 6.4.1). Path rules apply in this order: lockfile, generated/vendored, test, ci,
 * migration, docs, config, source. Rust `#[cfg(test)]` modules are detected per unit, not here.
 */
import type { FilterReason, Language, UnitKind } from '@remit/core';
import { type AttributeRule, attributeFor } from './gitattributes.js';
import { matchAny } from './glob.js';

export interface FileClass {
  kind: UnitKind;
  language: Language;
  filtered?: FilterReason;
}

export interface ClassifyContext {
  /** Parsed `.gitattributes` rules from the head tree. */
  attributes?: readonly AttributeRule[];
  /** The first lines of the head version, used to spot `@generated` headers. */
  headText?: string;
  /** True when the diff marks the file as binary. */
  binary?: boolean;
}

const LOCKFILES = [
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'Cargo.lock',
  'poetry.lock',
  'uv.lock',
  'Gemfile.lock',
  'go.sum',
  'npm-shrinkwrap.json',
  'bun.lockb',
  'composer.lock',
];

const VENDORED = ['vendor/', 'third_party/', '**/vendor/**', '**/third_party/**', '**/node_modules/**'];
const GENERATED = [
  'dist/',
  'build/',
  '**/dist/**',
  '**/build/**',
  '*.min.js',
  '*.min.css',
  '*.pb.*',
  '*_pb2.py',
  '*_pb2_grpc.py',
  '*.generated.*',
  '**/__generated__/**',
  '**/generated/**',
  '*.snap.js',
];
const TESTS = [
  '**/__tests__/**',
  '*.test.*',
  '*.spec.*',
  '**/test/**',
  '**/tests/**',
  'test_*.py',
  '*_test.py',
  '*_test.go',
  '**/__snapshots__/**',
  'conftest.py',
];
const CI = ['.github/workflows/**', '.gitlab-ci.yml', '.circleci/**'];
const MIGRATIONS = ['**/migrations/**', '**/migrate/**'];
const DOCS = ['*.md', '*.mdx', '*.rst', '*.txt', 'docs/**'];
const CONFIG = [
  '*.json',
  '*.yaml',
  '*.yml',
  '*.toml',
  '*.ini',
  '.env.example',
  'Dockerfile',
  '*.Dockerfile',
  '*.config.*',
  '.gitattributes',
  '.gitignore',
  '.editorconfig',
  '*.cfg',
];
const BUILD = [
  'Makefile',
  'CMakeLists.txt',
  '*.gradle',
  '*.gradle.kts',
  'BUILD',
  'BUILD.bazel',
  'WORKSPACE',
  '*.bzl',
  'build.rs',
  'setup.py',
  'justfile',
];
const ASSETS = [
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.svg',
  '*.ico',
  '*.webp',
  '*.woff',
  '*.woff2',
  '*.ttf',
  '*.otf',
  '*.mp4',
  '*.mp3',
  '*.wav',
  '*.pdf',
  '*.zip',
  '*.wasm',
];

const EXT_LANG: Record<string, Language> = {
  ts: 'ts',
  mts: 'ts',
  cts: 'ts',
  tsx: 'tsx',
  js: 'js',
  mjs: 'js',
  cjs: 'js',
  jsx: 'js',
  py: 'py',
  pyi: 'py',
  rs: 'rs',
};

/** Language from the file extension; `other` for anything tree-sitter does not parse here. */
export function languageOf(path: string): Language {
  const ext = /\.([A-Za-z0-9]+)$/.exec(path)?.[1]?.toLowerCase() ?? '';
  return EXT_LANG[ext] ?? 'other';
}

/** True when the first lines carry a common generated-code marker. */
export function hasGeneratedHeader(text: string): boolean {
  const head = text.split('\n', 8).join('\n');
  return /@generated\b|\bDO NOT EDIT\b|\bauto-?generated\b|\bCode generated by\b/i.test(head);
}

function basename(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1);
}

/** Classifies one file by path, attributes and header. */
export function classifyFile(path: string, ctx: ClassifyContext = {}): FileClass {
  const language = languageOf(path);
  if (ctx.binary) return { kind: 'binary', language, filtered: 'binary' };
  if (LOCKFILES.includes(basename(path))) return { kind: 'lockfile', language, filtered: 'lockfile' };

  const attrs = ctx.attributes ?? [];
  const vendoredAttr = attributeFor(attrs, path, 'linguist-vendored');
  const generatedAttr = attributeFor(attrs, path, 'linguist-generated');
  if (vendoredAttr === true || (vendoredAttr !== false && matchAny(path, VENDORED))) {
    return { kind: 'vendored', language, filtered: 'vendored' };
  }
  if (
    generatedAttr === true ||
    (generatedAttr !== false &&
      (matchAny(path, GENERATED) || (ctx.headText !== undefined && hasGeneratedHeader(ctx.headText))))
  ) {
    return { kind: 'generated', language, filtered: 'generated' };
  }

  if (matchAny(path, TESTS)) return { kind: 'test', language };
  if (matchAny(path, CI)) return { kind: 'ci', language };
  if (matchAny(path, MIGRATIONS)) return { kind: 'migration', language };
  if (matchAny(path, DOCS)) return { kind: 'docs', language };
  if (matchAny(path, CONFIG)) return { kind: 'config', language };
  if (matchAny(path, BUILD)) return { kind: 'build', language };
  if (matchAny(path, ASSETS)) return { kind: 'asset', language };
  return { kind: 'source', language };
}
