import { describe, expect, it } from 'vitest';
import { classifyFile, hasGeneratedHeader, languageOf } from './classify.js';
import { attributeFor, parseGitattributes } from './gitattributes.js';
import { matchGlob } from './glob.js';

describe('matchGlob', () => {
  it.each([
    ['src/a.min.js', '*.min.js', true],
    ['a.min.js', '*.min.js', true],
    ['docs/guide/x.md', 'docs/**', true],
    ['pkg/docs/x.md', 'docs/**', false],
    ['pkg/docs/x.md', '**/docs/**', true],
    ['src/__tests__/a.ts', '**/__tests__/**', true],
    ['build/out.js', '/build', true],
    ['src/build/out.js', '/build', false],
    ['vendor/lib/x.go', 'vendor/', true],
    ['a/b/vendor/x.go', 'vendor/', true],
    ['src/file.ts', 'src/*.ts', true],
    ['src/deep/file.ts', 'src/*.ts', false],
    ['a.ts', '?.ts', true],
    ['ab.ts', '?.ts', false],
    ['.github/workflows/ci.yml', '.github/workflows/**', true],
    ['x/a+b.ts', 'a+b.ts', true],
  ])('%s vs %s -> %s', (path, pattern, expected) => {
    expect(matchGlob(path, pattern)).toBe(expected);
  });
});

describe('gitattributes', () => {
  const rules = parseGitattributes(`# comment
[attr]binary -diff -merge -text
*.gen.ts linguist-generated
api/client.ts linguist-generated=true
api/keep.gen.ts -linguist-generated
third/** linguist-vendored eol=lf
docs/*.md !linguist-generated
`);

  it('parses set, unset and valued attributes', () => {
    expect(attributeFor(rules, 'x/a.gen.ts', 'linguist-generated')).toBe(true);
    expect(attributeFor(rules, 'api/client.ts', 'linguist-generated')).toBe(true);
    expect(attributeFor(rules, 'third/lib/x.js', 'eol')).toBe('lf');
    expect(attributeFor(rules, 'src/a.ts', 'linguist-generated')).toBeUndefined();
  });

  it('lets later rules win', () => {
    expect(attributeFor(rules, 'api/keep.gen.ts', 'linguist-generated')).toBe(false);
  });
});

describe('classifyFile', () => {
  it.each([
    ['pnpm-lock.yaml', 'lockfile', 'lockfile'],
    ['sub/Cargo.lock', 'lockfile', 'lockfile'],
    ['go.sum', 'lockfile', 'lockfile'],
    ['dist/index.js', 'generated', 'generated'],
    ['web/app.min.js', 'generated', 'generated'],
    ['proto/user.pb.go', 'generated', 'generated'],
    ['vendor/github.com/x/y.go', 'vendored', 'vendored'],
    ['third_party/lib.c', 'vendored', 'vendored'],
    ['src/__tests__/a.ts', 'test', undefined],
    ['src/a.test.ts', 'test', undefined],
    ['src/a.spec.tsx', 'test', undefined],
    ['tests/test_orders.py', 'test', undefined],
    ['pkg/orders_test.py', 'test', undefined],
    ['server/handler_test.go', 'test', undefined],
    ['src/__snapshots__/a.test.ts.snap', 'test', undefined],
    ['.github/workflows/ci.yml', 'ci', undefined],
    ['.gitlab-ci.yml', 'ci', undefined],
    ['.circleci/config.yml', 'ci', undefined],
    ['db/migrations/001_init.sql', 'migration', undefined],
    ['README.md', 'docs', undefined],
    ['docs/guide/setup.ts', 'docs', undefined],
    ['package.json', 'config', undefined],
    ['vitest.config.ts', 'config', undefined],
    ['Dockerfile', 'config', undefined],
    ['.env.example', 'config', undefined],
    ['Makefile', 'build', undefined],
    ['logo.png', 'asset', undefined],
    ['src/api/users.ts', 'source', undefined],
    ['cmd/main.go', 'source', undefined],
  ])('%s -> %s', (path, kind, filtered) => {
    const c = classifyFile(path);
    expect(c.kind).toBe(kind);
    expect(c.filtered).toBe(filtered);
  });

  it('honors linguist-generated and linguist-vendored from .gitattributes', () => {
    const attributes = parseGitattributes(
      'src/schema.ts linguist-generated\nlib/** linguist-vendored\ndist/keep.js -linguist-generated\n',
    );
    expect(classifyFile('src/schema.ts', { attributes })).toMatchObject({
      kind: 'generated',
      filtered: 'generated',
    });
    expect(classifyFile('lib/a.js', { attributes })).toMatchObject({
      kind: 'vendored',
      filtered: 'vendored',
    });
    expect(classifyFile('dist/keep.js', { attributes }).kind).toBe('source');
  });

  it('detects @generated headers', () => {
    expect(
      classifyFile('src/types.ts', { headText: '// @generated by protoc\nexport type A = 1;' }).kind,
    ).toBe('generated');
    expect(hasGeneratedHeader('# Code generated by sqlc. DO NOT EDIT.\n')).toBe(true);
    expect(hasGeneratedHeader('export const a = 1;\n// mentions @generated much later'.padStart(10))).toBe(
      true,
    );
    expect(hasGeneratedHeader('export const a = 1;\n')).toBe(false);
  });

  it('marks binaries first', () => {
    expect(classifyFile('src/a.ts', { binary: true })).toEqual({
      kind: 'binary',
      language: 'ts',
      filtered: 'binary',
    });
  });

  it.each([
    ['a.ts', 'ts'],
    ['a.mts', 'ts'],
    ['a.tsx', 'tsx'],
    ['a.jsx', 'js'],
    ['a.cjs', 'js'],
    ['a.py', 'py'],
    ['a.rs', 'rs'],
    ['a.go', 'other'],
    ['Makefile', 'other'],
  ])('languageOf(%s) = %s', (path, lang) => {
    expect(languageOf(path)).toBe(lang);
  });
});
